### ISSUE TITLE
Map editor should not allow territory names with lowercase letters

### ISSUE THREAD

**Issue by ghostelephant** [Riskrieg/map-editor#9]
In the map editor, users can give territories names with lowercase letters.  However, during gameplay when making claims, territory names are converted to uppercase.  This means any territories with lowercase letters in their names will be un-claimable.

This is probably just a matter of throwing a `.toUpperCase()` on the territory name after the user submits it, but before it gets saved.

**Comment by aaronjyoder** [comment]
This is now complete, in addition to #10, and will be released with version 2.7.2.
